version: '3.9'

services:
  fastapi:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build: .
    command: streamlit run streamlit_app.py --server.port 8501
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - fastapi
